language: java

branches:
  only:
  - master

jobs:
  include:
    - stage: build heroku rec app
      script:
        echo "buidling heroku rec application"
    - stage: run tests on rec app
      script:
        - cd tests/nr/
        - cd selenium-page-objects
        - mvn clean
        - mvn install
        - cd ../selenium-regression-tests
        - mvn clean
        - mvn test
    - stage: report test results
      script: echo "report test results"
    - stage: deploy heroku prod app
      script:
        - echo "deploy heroku prod app"

notifications:
  slack:
    on_success: always