language: java

branches:
  only:
  - master

script:
  - cd tests/nr/selenium-page-objects
  - mvn install
  - cd ../selenium-regression-tests
  - mvn test

notifications:
  slack:
    on_success: always