language: java

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key: 3a12d835-fb52-4977-946b-7a0c30a0bad5
  app:
    master: rec-clickclack-web
    production: clickclack-web

notifications:
  slack:
    on_success: always